# Generated by Django 5.0.4 on 2024-05-08 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpost_num_travelers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="date_period",
            new_name="end_date",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="home_photos",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
