# Generated by Django 5.0.4 on 2024-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_date_period_blogpost_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
        ),
    ]
