# Generated by Django 5.0.4 on 2024-06-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="receiver_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="sender_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
