# Generated by Django 5.0.4 on 2024-06-01 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_room_receiver_confirmed_room_sender_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room",
                to="messaging.room",
            ),
        ),
    ]
