# Generated by Django 5.0.4 on 2024-05-04 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appuser",
            old_name="addresse",
            new_name="street",
        ),
    ]
