# Generated by Django 5.0.4 on 2024-05-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_appuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="street",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
