# Generated by Django 5.0.4 on 2024-05-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_appuser_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="location",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="street",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
