# Generated by Django 5.0.4 on 2024-05-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_homephoto_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homephoto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
