# Generated by Django 5.0.4 on 2024-05-21 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_appuser_location_alter_appuser_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{5}$", "Postal code should contain exactly 5 digits"
                    )
                ],
            ),
        ),
    ]
