# Generated by Django 5.0.4 on 2024-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_appuser_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
